### Data encryption and Decryption
* Data Encryption :
   - Encyption is a security method in which information is encoded in such a way that only authorized user can read it.It uses encryption algorithm to generate ciphertext that can be read if decyption.
* Data Decyption :
   - Decyption is the process of taking encoded or encypted text and coverting it back into text that you or the computer can read and understand
* Types :
   - Symmetric(private key): It uses a single key that will be shared among the people who need to recive the message
* Asymmetric(Public key) :
   - Asymmetrical encryption uses a pair of public key and a private key to encrypt and decrypt message
* Write a function to generate key for encryption

In [1]:
#Function to generate key for encryption.
keypath='DataFiles/key.txt'
def genkey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
genkey(keypath)

In [15]:
#Function to decrypt a datafiles
keyfile='DataFiles/key.txt'
def dickeyfile(keyfile):
    key={}
    with open(keyfile,'r') as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
        return key
def encryMarksData(datafile,keyfile):
    #construct a dictionary for key data
    key=dickeyfile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
    with open('DataFiles/encryMarks.txt','w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                line+=key[n]
            f.write(line+'\n')
    return
datafile='DataFiles/marks.txt'
encryMarksData(datafile,keyfile)

In [28]:
#Function to decrypt the encrypted file
def decrypMarksData(encryptedfile,keyfile):
    key=dickeyfile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    with open(encryptedfile,'r') as f:
        encrypteddata=f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt','w') as f:
        for encyptedmark in encrypteddata:
            line=''
            for n in encyptedmark:
                line+=newkey[n]
                f.write(line+'\n')
    return
encryptedfile='DataFiles/encryptedMarks.txt'
import timeit
st=timeit.default_timer()
decrypMarksData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.0015665839996472641


##### Python Libraries For Data Science
* Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data. It involves many different disciplines like mathematical and statistical modelling, extracting data from it source and applying data visualization techniques. There are nearly 20 python libraries for Data Science. Top five python libraries are
* TensorFlow
* NumPy
* SciPy
* Pandas
* Matplotlib In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.
###### NumPy: (Numerical Python)
* Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion. \Ex: >>import numpy as np
###### NumPy Arrays
* NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists. There are three types of arrays called 1D, 2D and 3D arrays.
# Creating 1D and 2D arrays using numPy.

In [1]:
import numpy as np
a1=np.array([2,3,4,5,6])
print(a1)
print(type(a1))

[2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a2=np.array([[2,3,4],[5,6,7]])
print(a2)

[[2 3 4]
 [5 6 7]]


* program to print the given list into array

In [11]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
print(a)

['1' '2' '3' 'z']


In [13]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

* for example,the following code print 1d array between 1 to 15

In [14]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
import numpy as np
a2=np.arange(10000)
print(a2)

[   0    1    2 ... 9997 9998 9999]


In [19]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

* Create a 2D array and inspect size,shape,dimensions and dtype of the array

##### Inspect the structure and Content of array using “ndarrays”
* The most basic object in NumPy is the “ndarray” object or simply an “array”.
* The ndarray has important attributes. They are
   - ndarray.ndim: No of dimensions of array referred as “rank”.
   - ndarray.shape: Returns the length of the array in tuple.
   - ndarray.size: Returns the size of an array.
   - ndarray.dtype: We can create or specify “dtype” using standard Python types. NumPy provides      types like numpy.int32, numpy.int16, and numpy.float64
   - ndarray.itemsize: Returns the size in bytes of each element in an array
* Create a 2D Array and inspect size, shape, dimensions and dtype of the array.

In [10]:
import numpy as np
a1=np.random.randint(0,2,size=(3,3))
a1[2][2]
print('shape:',a1.shape)
print('size:',a1.size)
print('DType:',a1.dtype)
print('Item size:',a1.itemsize)
print('data:',a1.data)
print(a1,end="")

shape: (3, 3)
size: 9
DType: int32
Item size: 4
data: <memory at 0x00000175368C12D0>
[[1 0 1]
 [1 1 1]
 [0 1 1]]

In [21]:
a1=[[1,2,3,4],[5,6,7,8]]
a1=np.array(a1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
print('shape:',a1.shape)
print('size:',a1.size)
print('DType:',a1.dtype)
print('dimension:',a1.ndim)

shape: (2, 4)
size: 8
DType: int32
dimension: 2


In [26]:
#program to create an array by taking range of array and reshape it
import numpy as np
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
#reverse the array using slicing
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [28]:
arr[1::-1]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [30]:
#create an array of 1's.Take a list and convert it into 3D array and add 1 to each element in an array
import numpy as np
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.ones?      #used to knoe about that method just like help option

In [37]:
b=[[1,2,3],[10,9,8],[8,7,6]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10,  9,  8],
       [ 8,  7,  6]])

In [38]:
d=c+1
d

array([[ 2,  3,  4],
       [11, 10,  9],
       [ 9,  8,  7]])

* we can perform arithematic operatins in NumPy like add,sub,etc.,and ofcourse log,sin,cos,etc.,..

In [45]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,11).reshape(2,3)
print('A:',a)
print('B:',b,'\n')
print('add:',a+b)
print('div:',a/b)

A: [[1 2 3]
 [4 5 6]]
B: [[ 5  6  7]
 [ 8  9 10]] 

add: [[ 6  8 10]
 [12 14 16]]
div: [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


* Program for applying sin, cos and logarithms to arrays in NumPy

In [46]:
a = [1,2,3]
a1 = np.array(a)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
